same as for MBNMAtime

diff --git a/.github/workflows/check-standard.yaml b/.github/workflows/check-standard.yaml
--- a/.github/workflows/check-standard.yaml
+++ b/.github/workflows/check-standard.yaml
@@ -31,23 +31,45 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-      - name: Install jags (windows-latest)
+      # Install JAGS for Windows
+      - name: Install JAGS for Windows
         if: runner.os == 'Windows'
         run: |
-          curl.exe -L -o wjags.exe --url https://sourceforge.net/projects/mcmc-jags/files/latest/download
+          curl.exe -L -o wjags.exe https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Windows/JAGS-4.3.1.exe/download
           .\wjags.exe /S
           del wjags.exe
+
+          set "PATH=%PATH%;C:\Program Files\JAGS\JAGS-4.3.1\bin"
+
         shell: cmd
 
-      - name: Set up jags for macos
+      - name: Install JAGS for macOS
         if: matrix.config.os == 'macos-latest'
         run: |
-          brew install jags
+          set -e
+          if [[ "$(uname -m)" == "arm64" ]]; then
+            echo "Detected macOS-arm64 (Apple Silicon). Installing JAGS using .pkg file."
 
-      - name: Set up jags for ubuntu
+            # Download the .pkg file
+            curl -L -o JAGS-4.3.2.pkg https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Mac%20OS%20X/JAGS-4.3.2.pkg/download
+
+            # Install the package
+            sudo installer -pkg JAGS-4.3.2.pkg -target /
+
+          else
+            echo "Using Homebrew for JAGS installation on macOS Intel."
+            brew update
+            brew install jags
+          fi
+
+      # Install JAGS for Ubuntu
+      - name: Install JAGS for Ubuntu
         if: matrix.config.os == 'ubuntu-latest'
         run: |
-          sudo apt-get install jags
+          sudo apt-get update
+          sudo apt-get install -y jags
+          echo "Checking JAGS installation..."
+          jags --version || echo "JAGS installation failed!"
 
       - uses: r-lib/actions/setup-pandoc@v2
 
