jags install copied from MBNMAtime

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -4,10 +4,9 @@ on:
   push:
     branches: [main, master]
   pull_request:
+    branches: [main, master]
 
-name: R-CMD-check.yaml
-
-permissions: read-all
+name: R-CMD-check
 
 jobs:
   R-CMD-check:
@@ -30,7 +29,47 @@ jobs:
       R_KEEP_PKG_SOURCE: yes
 
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v3
+
+      # Install JAGS for Windows
+      - name: Install JAGS for Windows
+        if: runner.os == 'Windows'
+        run: |
+          curl.exe -L -o wjags.exe https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Windows/JAGS-4.3.1.exe/download
+          .\wjags.exe /S
+          del wjags.exe
+
+          set "PATH=%PATH%;C:\Program Files\JAGS\JAGS-4.3.1\bin"
+
+        shell: cmd
+
+      - name: Install JAGS for macOS
+        if: matrix.config.os == 'macos-latest'
+        run: |
+          set -e
+          if [[ "$(uname -m)" == "arm64" ]]; then
+            echo "Detected macOS-arm64 (Apple Silicon). Installing JAGS using .pkg file."
+
+            # Download the .pkg file
+            curl -L -o JAGS-4.3.2.pkg https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Mac%20OS%20X/JAGS-4.3.2.pkg/download
+
+            # Install the package
+            sudo installer -pkg JAGS-4.3.2.pkg -target /
+
+          else
+            echo "Using Homebrew for JAGS installation on macOS Intel."
+            brew update
+            brew install jags
+          fi
+
+      # Install JAGS for Ubuntu
+      - name: Install JAGS for Ubuntu
+        if: matrix.config.os == 'ubuntu-latest'
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y jags
+          echo "Checking JAGS installation..."
+          jags --version || echo "JAGS installation failed!"
 
       - uses: r-lib/actions/setup-pandoc@v2
 
@@ -48,4 +87,3 @@ jobs:
       - uses: r-lib/actions/check-r-package@v2
         with:
           upload-snapshots: true
-          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
